# Generated by Django 4.0.6 on 2022-07-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=20)),
            ],
        ),
    ]
