# Generated by Django 4.0.6 on 2022-07-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', default='', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(help_text='Comment ID', primary_key=True, serialize=False),
        ),
    ]
