# Generated by Django 4.0.6 on 2022-07-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
